from .caja import Caja
from .categoria import Categoria
from .cliente import Cliente
from .detalle_venta import DetalleVenta
from .producto import Producto
from .serie import Serie
from .tipo_afectacion import TipoAfectacion
from .tipo_comprobante import TipoComprobante
from .tipo_documento import TipoDocumento
from .usuario import Usuario
from .venta import Venta
