from .caja import Caja, CajaCreate, CajaUpdate
from .categoria import Categoria, CategoriaCreate, CategoriaUpdate
from .cliente import Cliente, ClienteCreate, ClienteUpdate
from .detalle_venta import DetalleVenta, DetalleVentaCreate, DetalleVentaUpdate
from .producto import Producto, ProductoCreate, ProductoUpdate
from .serie import Serie, SerieCreate, SerieUpdate
from .tipo_afectacion import TipoAfectacion, TipoAfectacionCreate, TipoAfectacionUpdate
from .tipo_comprobante import TipoComprobante, TipoComprobanteCreate, TipoComprobanteUpdate
from .tipo_documento import TipoDocumento, TipoDocumentoCreate, TipoDocumentoUpdate
from .usuario import Usuario, UsuarioCreate, UsuarioUpdate
from .venta import Venta, VentaCreate, VentaUpdate
