from .caja import *
from .categoria import *
from .cliente import *
from .detalle_venta import *
from .producto import *
from .serie import *
from .tipo_afectacion import *
from .tipo_comprobante import *
from .tipo_documento import *
from .usuario import *
from .venta import *
